const topics = {
  physics: {
    mechanics: [
      "units-&-measurements",
      "vector-algebra",
      "motion-in-a-straight-line",
      "motion-in-a-plane",
      "circular-motion",
      "laws-of-motion",
      "work-power-&-energy",
      "center-of-mass-and-collision",
      "rotational-motion",
      "properties-of-matter",
      "heat-and-thermodynamics",
      "simple-harmonic-motion",
      "waves",
      "gravitation",
    ],
    electricity: [
      "electrostatics",
      "current-electricity",
      "capacitor",
      "magnetic-effect-of-current",
      "magnetic-properties-of-matter",
      "electromagnetic-induction",
      "alternating-current",
      "electromagnetic-waves",
    ],
    optics: ["geometrical-optics", "wave-optics"],
    "modern-physics": [
      "atoms-and-nuclei",
      "dual-nature-of-radiation",
      "semiconductor",
      "communication-systems",
    ],
  },
  chemistry: {
    "physical-chemistry": [
      "some-basic-concepts-of-chemistry",
      "structure-of-atom",
      "redox-reactions",
      "gaseous-state",
      "chemical-equilibrium",
      "ionic-equilibrium",
      "solutions",
      "thermodynamics",
      "electrochemistry",
      "chemical-kinetics-and-nuclear-chemistry",
      "solid-state",
      "surface-chemistry",
    ],
    "inorganic-chemistry": [
      "periodic-table-&-periodicity",
      "chemical-bonding-&-molecular-structure",
      "isolation-of-elements",
      "hydrogen",
      "s-block-elements",
      "p-block-elements",
      "d-and-f-block-elements",
      "coordination-compounds",
      "salt-analysis",
      "environmental-chemistry",
    ],
    "organic-chemistry": [
      "basics-of-organic-chemistry",
      "hydrocarbons",
      "haloalkanes-and-haloarenes",
      "alcohols-phenols-and-ethers",
      "aldehydes-ketones-and-carboxylic-acids",
      "compounds-containing-nitrogen",
      "polymers",
      "biomolecules",
      "chemistry-in-everyday-life",
      "practical-organic-chemistry",
    ],
  },
  mathematics: {
    algebra: [
      "sets-and-relations",
      "logarithm",
      "quadratic-equation-and-inequalities",
      "sequences-and-series",
      "mathematical-induction",
      "binomial-theorem",
      "matrices-and-determinants",
      "permutations-and-combinations",
      "probability",
      "vector-algebra",
      "3d-geometry",
      "complex-numbers",
      "statistics",
      "mathematical-reasoning",
    ],
    trigonometry: [
      "trigonometric-ratio-and-identities",
      "trigonometric-equations",
      "inverse-trigonometric-functions",
      "properties-of-triangle",
      "height-and-distance",
    ],
    "coordinate-geometry": [
      "straight-lines-and-pair-of-straight-lines",
      "circle",
      "parabola",
      "ellipse",
      "hyperbola",
    ],
    calculus: [
      "functions",
      "limits-continuity-and-differentiability",
      "differentiation",
      "application-of-derivatives",
      "indefinite-integrals",
      "definite-integration",
      "area-under-the-curves",
      "differential-equations",
    ],
  },
};

export default topics;
